"""
Simple portfolio/risk backtest using latest signal snapshots.

Usage:
  python scripts/run_portfolio_backtest.py
  python scripts/run_portfolio_backtest.py --signals data/processed/signals_latest_snapshot.csv
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.forecasting.portfolio import (
    compute_signal_score,
    signal_to_weights,
    portfolio_var_95,
    apply_var_limit,
)
from src.forecasting.loaders import load_russian_yield_curve, load_chinese_yield_curve


def _load_signal_snapshot(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def _compute_proxy_returns(ru: pd.DataFrame, cn: pd.DataFrame) -> pd.DataFrame:
    # Use 10Y as duration proxy
    ru_col = "RU_10Y" if "RU_10Y" in ru.columns else ru.columns[0]
    cn_col = "CN_10Y" if "CN_10Y" in cn.columns else cn.columns[0]
    common = ru.index.intersection(cn.index)
    r = pd.DataFrame(index=common)
    # Duration-proxy returns: -delta yield
    r["RUB"] = -ru.loc[common, ru_col].diff().fillna(0.0) / 100.0
    r["CNY"] = -cn.loc[common, cn_col].diff().fillna(0.0) / 100.0
    return r


def main():
    ap = argparse.ArgumentParser(description="Run signal-driven portfolio backtest")
    ap.add_argument(
        "--signals",
        type=str,
        default="data/processed/signals_latest_snapshot.csv",
        help="Path to signal snapshot CSV generated by run_signals.py",
    )
    ap.add_argument("--var-limit", type=float, default=0.03, help="VaR(95%) limit per period")
    args = ap.parse_args()

    ru = load_russian_yield_curve()
    cn = load_chinese_yield_curve()
    if ru.empty or cn.empty:
        print("No RU/CN yield data. Run pipeline first.")
        return 1

    returns = _compute_proxy_returns(ru, cn)
    if returns.empty:
        print("No overlapping return data.")
        return 1

    snapshot = _load_signal_snapshot(Path(args.signals))
    signal_score = compute_signal_score(snapshot)

    naive_w = {"RUB": 0.5, "CNY": 0.5}
    disconnected_w = {"RUB": 0.6, "CNY": 0.4}
    strategy_w = signal_to_weights(signal_score, prev_weights=naive_w, max_turnover=0.30, liquidity_cap=0.80)

    vol_rub = float(returns["RUB"].std())
    vol_cny = float(returns["CNY"].std())
    corr = float(returns["RUB"].corr(returns["CNY"]))
    v = portfolio_var_95(strategy_w, vol_rub, vol_cny, corr)
    strategy_w = apply_var_limit(strategy_w, v, args.var_limit)

    def _portfolio_series(w):
        return w["RUB"] * returns["RUB"] + w["CNY"] * returns["CNY"]

    series = {
        "strategy": _portfolio_series(strategy_w),
        "naive_50_50": _portfolio_series(naive_w),
        "disconnected_60_40": _portfolio_series(disconnected_w),
    }

    summary_rows = []
    for name, s in series.items():
        cum = (1 + s).cumprod()
        sharpe = float((s.mean() / (s.std() + 1e-12)) * np.sqrt(12))
        drawdown = (cum / cum.cummax() - 1.0).min()
        var95 = float(np.quantile(-s, 0.95))
        summary_rows.append(
            {
                "strategy": name,
                "ann_sharpe": round(sharpe, 4),
                "max_drawdown": round(float(drawdown), 4),
                "var95_empirical": round(var95, 4),
                "mean_return": round(float(s.mean()), 6),
            }
        )

    summary = pd.DataFrame(summary_rows)
    out_dir = Path("data/processed")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_csv = out_dir / "portfolio_backtest_summary.csv"
    summary.to_csv(out_csv, index=False)

    print("Portfolio weights:")
    print(f"  strategy: {strategy_w}")
    print("\nBacktest summary:")
    print(summary.to_string(index=False))
    print(f"\nSaved: {out_csv}")
    return 0


if __name__ == "__main__":
    sys.exit(main())

