"""
Classical signal panel backtest with unified metrics.

Usage:
  python scripts/run_portfolio_backtest.py
  python scripts/run_portfolio_backtest.py --signals data/processed/signals_latest.csv
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.forecasting.portfolio import (
    signal_to_weights,
)
from src.forecasting.loaders import load_russian_yield_curve, load_chinese_yield_curve
from src.forecasting.backtest_metrics import (
    compute_proxy_returns,
    align_signal_to_next_return,
    compute_turnover,
    apply_transaction_costs,
    summarize_series,
    to_stats_row,
    bootstrap_mean_diff_ci,
    bootstrap_sharpe_diff_ci,
    paired_ttest,
)


def _load_signal_panel(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def _extract_classical_score_per_date(panel: pd.DataFrame) -> pd.Series:
    """
    Build a per-date classical signal score from spread/cip/factor signal columns.
    """
    if panel.empty:
        return pd.Series(dtype=float)
    if "date" not in panel.columns:
        return pd.Series(dtype=float)
    df = panel.copy()
    df["date"] = pd.to_datetime(df["date"])
    sig_cols = [
        c for c in df.columns
        if c.startswith("spread_signal_") or c.startswith("cip_signal_") or c in ("signal_RU", "signal_CN")
    ]
    if not sig_cols:
        return pd.Series(dtype=float)
    for c in sig_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0.0)
    grouped = df.groupby("date")[sig_cols].mean()
    score = grouped.mean(axis=1).clip(-1.0, 1.0)
    return score.sort_index()


def main():
    ap = argparse.ArgumentParser(description="Run classical signal-driven panel backtest")
    ap.add_argument(
        "--signals",
        type=str,
        default="data/processed/signals_latest.csv",
        help="Path to signal panel CSV generated by run_signals.py",
    )
    ap.add_argument("--cost-bps", type=float, default=5.0, help="Transaction cost in bps per turnover unit")
    ap.add_argument("--bootstrap", type=int, default=1000, help="Bootstrap iterations for CI")
    ap.add_argument("--returns-out", type=str, default="data/processed/portfolio_backtest_monthly_returns.csv")
    ap.add_argument("--inference-out", type=str, default="data/processed/portfolio_backtest_inference.csv")
    args = ap.parse_args()

    ru = load_russian_yield_curve()
    cn = load_chinese_yield_curve()
    if ru.empty or cn.empty:
        print("No RU/CN yield data. Run pipeline first.")
        return 1

    returns = compute_proxy_returns(ru, cn)
    if returns.empty:
        print("No overlapping return data.")
        return 1

    panel = _load_signal_panel(Path(args.signals))
    score = _extract_classical_score_per_date(panel)

    common_idx = returns.index.intersection(score.index)
    if common_idx.empty:
        print("No overlap between classical signals and returns.")
        return 1
    aligned = returns.loc[common_idx].copy()
    aligned["score_raw"] = score.loc[common_idx].astype(float)
    aligned["score"] = align_signal_to_next_return(aligned["score_raw"], aligned.index)

    weights = []
    prev = {"RUB": 0.5, "CNY": 0.5}
    for t, row in aligned.iterrows():
        w = signal_to_weights(float(row["score"]), prev_weights=prev, max_turnover=0.30, liquidity_cap=0.80)
        weights.append({"date": t, "w_rub": w["RUB"], "w_cny": w["CNY"]})
        prev = w
    wdf = pd.DataFrame(weights).set_index("date")
    aligned = aligned.join(wdf, how="left")
    aligned["strategy_gross_ret"] = aligned["w_rub"] * aligned["RUB"] + aligned["w_cny"] * aligned["CNY"]
    aligned["naive_gross_ret"] = 0.5 * aligned["RUB"] + 0.5 * aligned["CNY"]
    aligned["disc_gross_ret"] = 0.6 * aligned["RUB"] + 0.4 * aligned["CNY"]

    aligned["turnover"] = (
        (aligned["w_rub"].diff().abs().fillna(abs(aligned["w_rub"].iloc[0] - 0.5))) +
        (aligned["w_cny"].diff().abs().fillna(abs(aligned["w_cny"].iloc[0] - 0.5)))
    ) / 2.0
    aligned["strategy_net_ret"], aligned["strategy_cost"] = apply_transaction_costs(
        aligned["strategy_gross_ret"], aligned["turnover"], cost_bps=args.cost_bps
    )
    aligned["naive_signal"] = 1.0
    aligned["disc_signal"] = 1.0
    aligned["naive_turnover"] = 0.0
    aligned["disc_turnover"] = 0.0
    aligned["naive_net_ret"], aligned["naive_cost"] = apply_transaction_costs(
        aligned["naive_gross_ret"], pd.Series(0.0, index=aligned.index), cost_bps=args.cost_bps
    )
    aligned["disc_net_ret"], aligned["disc_cost"] = apply_transaction_costs(
        aligned["disc_gross_ret"], pd.Series(0.0, index=aligned.index), cost_bps=args.cost_bps
    )

    st = summarize_series(
        strategy_name="strategy",
        net_returns=aligned["strategy_net_ret"],
        active_signal=aligned["score"],
        turnover=aligned["turnover"],
        costs=aligned["strategy_cost"],
    )
    nv = summarize_series(
        strategy_name="naive_50_50",
        net_returns=aligned["naive_net_ret"],
        active_signal=aligned["naive_signal"],
        turnover=pd.Series(0.0, index=aligned.index),
        costs=aligned["naive_cost"],
    )
    ds = summarize_series(
        strategy_name="disconnected_60_40",
        net_returns=aligned["disc_net_ret"],
        active_signal=aligned["disc_signal"],
        turnover=pd.Series(0.0, index=aligned.index),
        costs=aligned["disc_cost"],
    )
    st_row = to_stats_row(st)
    nv_row = to_stats_row(nv)
    ds_row = to_stats_row(ds)
    for row in (st_row, nv_row, ds_row):
        row["benchmark"] = "naive_50_50"
        row["excess_ann_return_vs_benchmark"] = round(row["ann_return"] - nv_row["ann_return"], 6)
        row["sharpe_delta_vs_benchmark"] = round(row["ann_sharpe"] - nv_row["ann_sharpe"], 6)
    summary = pd.DataFrame([st_row, nv_row, ds_row])

    mean_diff, mean_lo, mean_hi = bootstrap_mean_diff_ci(
        aligned["strategy_net_ret"], aligned["naive_net_ret"], n_boot=args.bootstrap
    )
    sharpe_diff, sh_lo, sh_hi = bootstrap_sharpe_diff_ci(
        aligned["strategy_net_ret"], aligned["naive_net_ret"], n_boot=args.bootstrap
    )
    t_stat, p_val = paired_ttest(aligned["strategy_net_ret"], aligned["naive_net_ret"])
    inference = pd.DataFrame(
        [
            {
                "comparison": "strategy_vs_naive_50_50",
                "mean_return_diff": round(mean_diff, 8) if pd.notna(mean_diff) else mean_diff,
                "mean_diff_ci_low": round(mean_lo, 8) if pd.notna(mean_lo) else mean_lo,
                "mean_diff_ci_high": round(mean_hi, 8) if pd.notna(mean_hi) else mean_hi,
                "sharpe_diff": round(sharpe_diff, 6) if pd.notna(sharpe_diff) else sharpe_diff,
                "sharpe_diff_ci_low": round(sh_lo, 6) if pd.notna(sh_lo) else sh_lo,
                "sharpe_diff_ci_high": round(sh_hi, 6) if pd.notna(sh_hi) else sh_hi,
                "paired_t_stat": round(t_stat, 6) if pd.notna(t_stat) else t_stat,
                "paired_t_pvalue": round(p_val, 6) if pd.notna(p_val) else p_val,
                "n_obs": int(len(aligned)),
                "cost_bps": float(args.cost_bps),
            }
        ]
    )

    out_dir = Path("data/processed")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_csv = out_dir / "portfolio_backtest_summary.csv"
    summary.to_csv(out_csv, index=False)
    returns_out = Path(args.returns_out)
    aligned.to_csv(returns_out, index_label="date")
    inference_out = Path(args.inference_out)
    inference.to_csv(inference_out, index=False)

    print("Classical panel backtest summary:")
    print(summary.to_string(index=False))
    print(f"\nSaved: {out_csv}")
    print(f"Saved: {returns_out}")
    print(f"Saved: {inference_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())

